import type { Workflow } from "@/types/workflow";

export function generateAirflowDag(workflow: Workflow): string {
  const { nodes = [], edges = [] } = workflow.dagDefinition || {};
  const dagId = workflow.airflowDagId || `bgp_${workflow.workflowId}`;
  const schedule = workflow.cronExpression || "None";

  // Build dependency map
  const deps: Record<string, string[]> = {};
  for (const edge of edges) {
    if (!deps[edge.target]) deps[edge.target] = [];
    deps[edge.target].push(edge.source);
  }

  let tasks = "";
  for (const node of nodes) {
    const taskId = node.id.replace(/[^a-zA-Z0-9_]/g, "_");
    const data = node.data || {};

    if (node.type === "sync") {
      tasks += `
    ${taskId} = PythonOperator(
        task_id="${taskId}",
        python_callable=trigger_sync_task,
        op_kwargs={"task_id": "${data.syncTaskId || ""}"},
    )
`;
    } else if (node.type === "sql") {
      const sql = (data.sql || "SELECT 1").replace(/"/g, '\\"').replace(/\n/g, "\\n");
      tasks += `
    ${taskId} = PythonOperator(
        task_id="${taskId}",
        python_callable=execute_redshift_sql,
        op_kwargs={"sql": "${sql}"},
    )
`;
    } else if (node.type === "python") {
      const script = (data.script || "pass").replace(/"/g, '\\"').replace(/\n/g, "\\n");
      tasks += `
    ${taskId} = PythonOperator(
        task_id="${taskId}",
        python_callable=run_custom_script,
        op_kwargs={"script": "${script}"},
    )
`;
    }

    if (data.retryCount) {
      tasks += `    ${taskId}.retries = ${data.retryCount}\n`;
    }
    if (data.timeout) {
      tasks += `    ${taskId}.execution_timeout = timedelta(seconds=${data.timeout})\n`;
    }
  }

  // Build dependency lines
  let depLines = "";
  for (const edge of edges) {
    const src = edge.source.replace(/[^a-zA-Z0-9_]/g, "_");
    const tgt = edge.target.replace(/[^a-zA-Z0-9_]/g, "_");
    depLines += `    ${src} >> ${tgt}\n`;
  }

  // Find leaf nodes (no outgoing edges) to attach callback
  const sources = new Set(edges.map((e: any) => e.source));
  const allIds = nodes.map((n: any) => n.id);
  const leafNodes = allIds.filter((id: string) => !sources.has(id));
  const leafTaskIds = leafNodes.map((id: string) => id.replace(/[^a-zA-Z0-9_]/g, "_"));

  return `"""Auto-generated by BigData Governance Platform"""
from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator
import boto3
import json
import time

region = "${process.env.AWS_REGION || "us-east-1"}"
glue = boto3.client("glue", region_name=region)
redshift = boto3.client("redshift-data", region_name=region)
WORKFLOW_ID = "${workflow.workflowId}"

def _update_workflow_status(status):
    dynamodb = boto3.resource("dynamodb", region_name=region)
    now = datetime.utcnow().isoformat() + "Z"
    dynamodb.Table("bgp-workflows").update_item(
        Key={"userId": "default-user", "workflowId": WORKFLOW_ID},
        UpdateExpression="SET lastRunStatus = :s, updatedAt = :t",
        ExpressionAttributeValues={":s": status, ":t": now},
    )

def _update_run_record(run_id, status, context=None):
    dynamodb = boto3.resource("dynamodb", region_name=region)
    now = datetime.utcnow().isoformat() + "Z"
    try:
        dag_run = context.get("dag_run") if context else None
        duration = 0
        started_at = now
        if dag_run and dag_run.start_date:
            duration = int((datetime.utcnow() - dag_run.start_date.replace(tzinfo=None)).total_seconds())
            started_at = dag_run.start_date.strftime("%Y-%m-%dT%H:%M:%S.000Z")
        # Determine trigger type from run_id
        triggered_by = "schedule" if run_id.startswith("scheduled__") else "manual"
        error_msg = None
        if status == "failed" and context:
            error_msg = str(context.get("exception", ""))[:500] or None
        # Upsert: creates record for MWAA-scheduled runs, updates for manual runs
        item = {
            "taskId": WORKFLOW_ID, "runId": run_id, "taskType": "workflow",
            "status": status, "startedAt": started_at, "finishedAt": now,
            "duration": duration, "triggeredBy": triggered_by,
            "airflowDagId": "${dagId}",
        }
        if error_msg:
            item["error"] = error_msg
        dynamodb.Table("bgp-task-runs").put_item(Item=item)
    except Exception as e:
        print(f"Failed to update run record: {e}")

def on_success(**kwargs):
    _update_workflow_status("succeeded")
    run_id = kwargs.get("dag_run").run_id if kwargs.get("dag_run") else None
    if run_id:
        _update_run_record(run_id, "succeeded", kwargs)

def on_failure(context):
    _update_workflow_status("failed")
    run_id = context.get("dag_run").run_id if context.get("dag_run") else None
    if run_id:
        _update_run_record(run_id, "failed", context)

def trigger_sync_task(task_id, **kwargs):
    """Start a Glue sync job via AWS API (no HTTP dependency on platform)"""
    dynamodb = boto3.resource("dynamodb", region_name=region)
    task = dynamodb.Table("bgp-sync-tasks").get_item(Key={"userId": "default-user", "taskId": task_id}).get("Item")
    if not task:
        raise Exception(f"Sync task {task_id} not found")
    job_name = task.get("glueJobName")
    if not job_name:
        raise Exception(f"Sync task {task_id} has no Glue job. Run it from the platform first.")
    run = glue.start_job_run(JobName=job_name)
    run_id = run["JobRunId"]
    print(f"Started Glue job {job_name}, run {run_id}")
    # Poll until complete
    while True:
        status = glue.get_job_run(JobName=job_name, RunId=run_id)["JobRun"]["JobRunState"]
        if status in ("SUCCEEDED", "FAILED", "STOPPED", "ERROR", "TIMEOUT"):
            break
        time.sleep(15)
    if status != "SUCCEEDED":
        raise Exception(f"Glue job {job_name} run {run_id} ended with {status}")
    print(f"Glue job {job_name} completed: {status}")

def execute_redshift_sql(sql, **kwargs):
    resp = redshift.execute_statement(WorkgroupName="bgp-workgroup", Database="dev", Sql=sql)
    stmt_id = resp["Id"]
    while True:
        desc = redshift.describe_statement(Id=stmt_id)
        if desc["Status"] in ("FINISHED", "FAILED", "ABORTED"):
            break
        time.sleep(2)
    if desc["Status"] != "FINISHED":
        raise Exception(f"Redshift SQL failed: {desc.get('Error','')}")

def run_custom_script(script, **kwargs):
    exec(script)

with DAG(
    dag_id="${dagId}",
    schedule_interval=${schedule === "None" ? "None" : `"${schedule}"`},
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=["bgp"],
    on_failure_callback=on_failure,
) as dag:
${tasks}
    _status_done = PythonOperator(
        task_id="_status_done",
        python_callable=on_success,
        trigger_rule="all_success",
    )

${depLines ? `    # Dependencies\n${depLines}` : ""}
    # All leaf tasks -> status callback
${leafTaskIds.length > 0 ? `    [${leafTaskIds.join(", ")}] >> _status_done` : ""}`;
}
